### ISSUE TITLE
Automatically include jsdom?

### ISSUE THREAD

**Issue by mesqueeb** [azu/safe-marked#5]
Hi @azu 
I was intrigued by your comment here:
https://github.com/markedjs/marked/pull/1519#issuecomment-510062918

> @UziTech Yes, I know.
> 
> I've tried to use marked@0.7 and [DOMPurify](https://github.com/cure53/DOMPurify), but this combination has a bit complex context.
> Because, [DOMPurify](https://github.com/cure53/DOMPurify) does not work on Node.js without [jsdom](https://github.com/jsdom/jsdom).
> 
> * marked is universal/isomophic library
> * [DOMPurify](https://github.com/cure53/DOMPurify) is not universal/isomophic library
>   
>   * It require [jsdom](https://github.com/jsdom/jsdom) for Node.js
> 
> The browser enviroment does not need jsdom, but Node.js env does need jsdom.
> It require a bit complex code.
> 
> ```js
> if(THIS_ENV_IS_NODE){
>   return marked + dompurify + jsdom
> } else{
>   return marked + dompurify
> }
> ```
> 
> So, I've created a wrapper library for optimizing Browser and Node.js.
> 
> * https://github.com/azu/safe-marked
> 
> [safe-marked](https://github.com/azu/safe-marked) is a wrapper library of marked, [DOMPurify](https://github.com/cure53/DOMPurify), and [jsdom](https://github.com/jsdom/jsdom).
> Also, safe-marked define ['browser' field in package.json](https://github.com/defunctzombie/package-browser-field-spec) for optimizing browser bundle.
> [The browser entry point](https://github.com/azu/safe-marked/blob/master/src/browser.ts) does not include jsdom.
> 
> This wrapper aim to reduce pacakge size for browser.
> 
> ```
>   package           size      minified  gzipped
>   safe-marked       90.15 KB  39.36 KB  13.82 KB (browser bundle size)
>   marked@0.7.0      45.05 KB  23.87 KB  7.87 KB
>   dompurify@1.0.11  45.21 KB  15.3 KB   5.99 KB
>   
>   # Other Markdown library  
>   markdown-it@9.0.0  325.52 KB  92.69 KB  32.77 KB
>   showdown@1.9.0     157.28 KB  71.06 KB  23.55 KB
> ```
> 
> ## Conclusion
> The documentation just say following
> 
> > Marked does not sanitize the output HTML. Please use a sanitize library, like DOMPurify (recommended), sanitize-html or insane on the output HTML! 🚨
> 
> Afte using marked + DOMPurify, I feed that it is hard to use `marked` safety.
> I think that we need to improve documentation about the usage of sanitizing.
> Or just come back to support `sanitize` option...
> 
> However, The documentation is not fundamental solution.
> 
> Thanks.
> 
> 📝 Note: The size of recommentation libraries :
> 
> [sanitize-html](https://github.com/apostrophecms/sanitize-html) is too large. [insane](https://github.com/bevacqua/insane) looks like that is not maintained and have [some problem](https://github.com/bevacqua/insane/issues/9).
> So, I've selected [DOMPurify](https://github.com/cure53/DOMPurify). DOMPurify is maintained by security company.
> 
> ```
>   package               size      minified   gzipped
>   dompurify@1.0.11      45.21 KB  15.3 KB    5.99 KB
>   sanitize-html@1.20.1  1.02 MB   210.06 KB  64.81 KB
>   insane@2.6.2          18.61 KB  4.64 KB    1.9 KB
> ```
> 
> Also, I love package size of `marked` ❤️

However, does `safe-marked` include JSDom by default? If I don't use SSR in an SPA of mine, I might not need JSDom.

**Comment by azu** [comment]
safe-marked define [browser field](https://github.com/defunctzombie/package-browser-field-spec).
In other word, safe-marked pacakge includes two type of entry point.

- https://github.com/azu/safe-marked/blob/cfb1d1ee54e48c611fd4c07483c9468080bfc107/package.json#L29

So, browser entrypoint does not includes jsdom. (just use marked + dompurify)

- https://github.com/azu/safe-marked/blob/master/src/browser.ts

webpack support `browser` field and the output bundle does not includes jsdom.
https://webpack.js.org/configuration/resolve/#resolvemainfields

Does my answer make sense?
